=== joanmxx/DAW-LMISGI-JoanMiquelPedrero/Practica 4.2/cataleg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="genereType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Música clásica"/>
      <xs:enumeration value="Jazz"/>
      <xs:enumeration value="Blues"/>
      <xs:enumeration value="Góspel"/>
      <xs:enumeration value="Soul"/>
      <xs:enumeration value="Pop"/>
      <xs:enumeration value="Rock and Roll"/>
      <xs:enumeration value="Country"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="sexeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="home"/>
      <xs:enumeration value="dona"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="cataleg">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="single"/>
          <xs:element ref="album"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="single">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titol" type="xs:string"/>
        <xs:element name="descripcio" type="xs:string" minOccurs="0"/>
        <xs:element name="pais" type="xs:string"/>
        <xs:element name="idioma" type="xs:string"/>
        <xs:element name="genere" type="genereType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="grup" type="xs:string"/>
        <xs:element name="membres">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="membre" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nom" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="sexe" type="sexeType" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="durada" type="xs:decimal"/>
      </xs:sequence>
      <xs:attribute name="codi" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="album">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titol" type="xs:string"/>
        <xs:element name="descripcio" type="xs:string" minOccurs="0"/>
        <xs:element name="pais" type="xs:string"/>
        <xs:element name="idioma" type="xs:string"/>
        <xs:element name="genere" type="genereType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="grup" type="xs:string"/>
        <xs:element name="membres">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="membre" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nom" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="sexe" type="sexeType" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="numero_cançons" type="xs:int"/>
        <xs:element name="titols_cançons">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="canço" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titol_canço" type="xs:string"/>
                    <xs:element name="durada_canço" type="xs:decimal"/>
                  </xs:sequence>
                  <xs:attribute name="numero" type="xs:int" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="codi" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== joanmxx/DAW-LMISGI-JoanMiquelPedrero/Practica 4.2/XML 4.2.xml
﻿<?xml version="1.0" encoding="UTF-8"?>
<cataleg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="cataleg.xsd">


  <single codi="S001">
    <titol>Cançó única</titol>
    <descripcio>Una cançó d'exemple</descripcio>
    <pais>Espanya</pais>
    <idioma>Català</idioma>
    <genere>Pop</genere>
    <grup>Grup X</grup>
    <membres>
      <membre sexe="home">
        <nom>Joan</nom>
      </membre>
      <membre sexe="dona">
        <nom>Ana</nom>
      </membre>
    </membres>
    <durada>3.5</durada>
  </single>

  <album codi="A001">
    <titol>Àlbum d'exemple</titol>
    <descripcio>Un àlbum amb diverses cançons</descripcio>
    <pais>EEUU</pais>
    <idioma>Anglès</idioma>
    <genere>Jazz</genere>
    <grup>Grup Y</grup>
    <membres>
      <membre sexe="home">
        <nom>John</nom>
      </membre>
      <membre sexe="dona">
        <nom>Mary</nom>
      </membre>
    </membres>
    <numero_cançons>2</numero_cançons>
    <titols_cançons>
      <canço numero="1">
        <titol_canço>Cançó 1</titol_canço>
        <durada_canço>4.2</durada_canço>
      </canço>
      <canço numero="2">
        <titol_canço>Cançó 2</titol_canço>
        <durada_canço>3.8</durada_canço>
      </canço>
    </titols_cançons>
  </album>

</cataleg>
