=== joanmxx/DAW-LMISGI-JoanMiquelPedrero/Practica 4.1/cataleg.dtd
<!ELEMENT cataleg (single*, album*)>

<!ELEMENT single (titol, descripcio, pais, idioma, genere, grup, membres, durada)>
<!ATTLIST single codi ID #REQUIRED>

<!ELEMENT album (titol, descripcio, pais, idioma, genere, grup, membres, numero_cançons, titols_cançons)>
<!ATTLIST album codi ID #REQUIRED>

<!ELEMENT titols_cançons (canço+)>

<!ELEMENT canço (titol_canço, durada_canço)>
<!ATTLIST canço numero CDATA #REQUIRED>

<!ELEMENT titol (#PCDATA)>

<!ELEMENT descripcio (#PCDATA)>

<!ELEMENT pais (#PCDATA)>

<!ELEMENT idioma (#PCDATA)>

<!ELEMENT grup (#PCDATA)>

<!ELEMENT membres (membre+)>

<!ELEMENT membre (nom)>
<!ATTLIST membre sexe (home | dona) #REQUIRED>

<!ELEMENT nom (#PCDATA)>

<!ELEMENT durada (#PCDATA)>

<!ELEMENT numero_cançons (#PCDATA)>

<!ELEMENT titol_canço (#PCDATA)>

<!ELEMENT durada_canço (#PCDATA)>

<!ELEMENT genere (#PCDATA)>

=== joanmxx/DAW-LMISGI-JoanMiquelPedrero/Practica 4.1/4.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cataleg SYSTEM "cataleg.dtd">
<cataleg>
    <single codi="S001">
        <titol>Canco A</titol>
        <descripcio>Una canco de pop</descripcio>
        <pais>Espanya</pais>
        <idioma>Espanyol</idioma>
        <genere>Pop</genere>
        <grup>Grup X</grup>
        <membres>
            <membre sexe="home">
                <nom>Nom 1</nom>
            </membre>
            <membre sexe="dona">
                <nom>nom 2</nom>
            </membre>
        </membres>
        <durada>3</durada>
    </single>


    <album codi="A001">
        <titol>Album B</titol>
        <descripcio>Un album de rock</descripcio>
        <pais>Espanya</pais>
        <idioma>Angles</idioma>
        <genere>Rock</genere>
        <grup>Grup Y</grup>
        <membres>
            <membre sexe="home">
                <nom>nom  4</nom>
            </membre>
            <membre sexe="dona">
                <nom>nom 4</nom>
            </membre>
        </membres>
        <numero_cançons>3</numero_cançons>
        <titols_cançons>
            <canço numero="1">
                <titol_canço>Cançó 1</titol_canço>
                <durada_canço>4</durada_canço>
            </canço>
            <canço numero="2">
                <titol_canço>Cançó 2</titol_canço>
                <durada_canço>5</durada_canço>
            </canço>
            <canço numero="3">
                <titol_canço>Cançó 3</titol_canço>
                <durada_canço>6</durada_canço>
            </canço>
        </titols_cançons>
    </album>
</cataleg>
